# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: holochain:holonix/latest.master
    steps:
      - checkout
      - run: nix-shell --run 'sandbox-test'

# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - build
